### PR TITLE
Drop `rolify` gem

### PR DESCRIPTION
**Pull request by dixpac**
I don't think we need `rolify` gem for the following reasons

1. We don't have any advanced roles in the system, just basic roles on
the user.
2. New developers are having a hard time to figure out how `rolify` works
3. Since we don't have complex roles, we don't need multiple tables for
roles(rolify implementation) and hence alyways executing unecessary db
queries.
4. In our use case we don't need new gem to maintain.

===============================================================

Since our roles are simple atm, this PR removes `rolify` and adds simple
`role` column on the users which is powered by `Rails enum`.

If you need to check weather user has specific role 
`user.admin? or user.member?`

If you need to list all users with specific role
`User.admin or User.member`

If you need to change the role
`user.admin! #=> changes the role to admin on the user instance`

Default role is `member` if not specified otherwise one the `user`
If in the future we feel need to introduce `roles` table it could be
done easily inside the migration.

### CODE REVIEW

**Review by pollygee — APPROVED** [review]
Wow yeah that's a lot cleaner!

**Comment by dixpac** [comment]
@pollygee @abronkema  can 1 user hold 2 roles, for example can I be `volunteer and member`?

**Comment by dixpac** [comment]
Thinking about the 2 roles use case, does that even makes sense how one user can hold 2 roles, it would be almost impossible to figure it out role context in which I act, if for example I’m `admin and member`…admin still beats member in permissions.

Only case where we might need this “mix-case” is on carrier checkout, where we only list members in the dropdown, but we can easily show everyone if we want :)

**Comment by corprew** [comment]
It's a normal feature of RBAC-based (Role Based Access Control)  systems that a user can have multiple roles, and the permissions of the user are the combination of everything that the user has the right to do.  So, in this case, a user with [member, admin] has the right to do something if a member or a admin can do it, which is why rolify has those methods for determining access.

The main idea is that RBAC is an additive system -- https://searchsecurity.techtarget.com/definition/role-based-access-control-RBAC -- so that the users have the combined permission of all their roles.

Here, we can get around that by saying that all  volunteers are members and all admins are members and volunteers so they have those rights, but really what we're doing there is compressing the roles.  We can probably get away with that, but in the future if the system needs to add more roles (like billing, or system admin), things will get complex

**Pull request merged**
