### PR TITLE
Layout

### PR DESCRIPTION
**Pull request by kaziski**
### Description
Added a sidebar that links to index pages (@cattywampus had me started working on this at R4G Issue ticket was never created for this.)
   
* New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by yarmiganosca** [comment]
Any chance you can post before and after screenshots? I find that very helpful when I'm making visual PRs.

**Comment by kaziski** [comment]
location-before

location-after

@yarmiganosca , Like this?

**Comment by kaziski** [comment]
category-before
category-after

I didn't style the side bar. If there is a mock one the designer made, I'd be happy to try!

**Comment by yarmiganosca** [comment]
This is fine. I just wanted to actually see the change.

**Pull request merged**
