### PR TITLE
Add asterisk to user registration form.

### LINKED ISSUE #78: User registration form: required fields aren't indicated
**Describe the bug**
When signing up for the first time, I had not visual indication that all fields were required until I received a list of errors after clicking "Sign up". Visual users, as well as screen reader users are given no heads up that they need to fill it all in, even though we assume it makes sense.

**To Reproduce**
1. Go to Sign Up page.
2. Partially fill out form.
4. See error.

**Expected behavior**
With no indication as to what's required or optional, I think most of these fields are optional, with the exception of the email and password fields.

If required, a screen reader user will expect to hear their screen reader announce "field required". A visual user will expect to see "*", "(required)", or "(optional)" written next to the label.

**Screenshots**
Screen Shot 2019-10-05 at 4 37 15 PM

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Version: 69

**Additional context**
This is an accessibility and usability issue. Screen reader users are not warned with a `required` or `aria-required` attribute. Visual users with cognitive disabilities as well as people without may become frustrated when it doesn't work for them the first time, and they're presented with a list of errors at the top.

### PR DESCRIPTION
**Pull request by enderahmetyurt**
Resolves #78

### CODE REVIEW

**Comment by yarmiganosca** [comment]
Thanks for your contribution!

You might consider adding `required: true` to the field helper method invocations. That will set the `required` html attribute on the generated `input` tags, which will help screen readers as mentioned in the issue. I'm not sure screen readers will communicate that a field is required to their user solely based on the existence of a css class.

**Comment by pollygee** [comment]
@enderahmetyurt I see this is your first time contributing!!! Thanks so much!

Are you able to make the changes @yarmiganosca has requested so we can get this merged in?

**Comment by enderahmetyurt** [comment]
Hi @pollygee I will change them next week 🙏

**Comment by pollygee** [comment]
Hi @enderahmetyurt! Just a heads up we have merged a lot of changes.  So can you please be sure to merge master into your branch and take care of any conflicts :) . Thanks so much!

**Comment by pollygee** [comment]
@enderahmetyurt do you still plan to work on this?  Just checking in.  Thanks!

**Comment by enderahmetyurt** [comment]
> @enderahmetyurt do you still plan to work on this? Just checking in. Thanks!

@pollygee sorry for latency. It was very hard week for me. I will do it in this week 🙏

**Review by pollygee — APPROVED** [review]

**Comment by pollygee** [comment]
Looks great thanks @enderahmetyurt!!  I appreciate your efforts, hope this week is better than last!

**Pull request merged**
