### PR TITLE
Fix duplicated notice

### LINKED ISSUE #90: Don't show sign up / sign in flash messages twice
**Describe the bug**
Currently when a user signs up or signs it, the flash message is shown twice. I think both of the issues can be resolved with one solution, seems they are related.

**To Reproduce**
If I click on the "Sign Up" button when i'm logged in, I get shown this message twice: "You are already signed up".

If I click on a navigation button while logged out, I am shown "You need to sign in or sign up before continuing" twice as well.

**Expected behavior**
The expected behavior would be for those messages to be shown once, not twice

**Screenshots**
Screen Shot 2019-10-09 at 9 23 04 AM
Screen Shot 2019-10-09 at 9 22 50 AM

### PR DESCRIPTION
**Pull request by JuarezLustosa**
Resolves #90 

- Removed a <p>, was duplicating message. 

* Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Teste feature increased

### CODE REVIEW

**Comment by dixpac** [comment]
LGTM! Just resolve merge conflicts

**Review by valeriecodes — APPROVED** [review]

**Comment by pollygee** [comment]
@JuarezLustosa welcome to the project!  Thanks so much for contributing.  Are you able to resolve the merge conflict so I can merge in your code?  Thanks a bunch!

**Comment by JuarezLustosa** [comment]
> @JuarezLustosa welcome to the project! Thanks so much for contributing. Are you able to resolve the merge conflict so I can merge in your code? Thanks a bunch!

Done! @pollygee. Sorry, @dixpac did all the changes.

**Comment by abronkema** [comment]
Thanks @JuarezLustosa ! 👏

**Pull request merged**
