### PR TITLE
Change category index to show subcategories as collapsed table

### LINKED ISSUE #109: Update /categories view to show Parent
In `/categories`, the view is currently confusing as the Parent categories and subcategories are listed inline with each other. 

image

We need to change the `/categories` view so that its default view lists _only_ Parent categories.

When a Parent category is clicked, we should then display all associated sub-categories assigned to that Parent.

### PR DESCRIPTION
**Pull request by mauricio-prl**
Resolves https://github.com/rubyforgood/babywearing/issues/109

### Description
This PR is just changing the category index, to show the subcategories as collapsed tables. 

### How Has This Been Tested?
Visit categories_path, then look for the categories child, that should not exist. After click on "+", look for the categories child again, and shuld find it.

### Screenshots
babywearing1
babywearing2

### CODE REVIEW

**Comment by pollygee** [comment]
Thanks!!  I think this looks good, I like the functionality.  I think we can think about styling differently, the + button looks a bit bulky to me but I think for this issue we just need it working and we can make it prettier later!   @ludamillion do you have any opinions about the button?

We def need some tests, and looks like you have one test that's failing but then we'll be good.

**Comment by mauricio-prl** [comment]
@pollygee I'm glad you liked it! As promised I finished the tests, I took the liberty to fix the carriers name, in carriers index. And about the styling, please let me know what you want. If you have some mock I will be happy to apply it.

**Comment by ludamillion** [comment]
Yeah, that '+' button looks like bulky to me as well. I think in this context a circle button could work and personally I'd add a little more spacing between the button and the text. It would also be good if we could get the edit/destroy links to align when the sub-list is expanded.

All in all though this looks pretty good to me. Will this jive with the sb-admin-2 theme changes?

**Comment by mauricio-prl** [comment]
@pollygee @ludamillion concerning the buttons, do you think they are better than before?
babywearing5

**Comment by pollygee** [comment]
Looks great @m-pereira !!  Thanks so much.  Almost there! 
@ludamillion makes a really good point, we've added a new theme.  Can you please merge master into your branch and see what that looks like and share some more screenshots?

**Comment by mauricio-prl** [comment]
After merge: 
babywearing6
babywearing7

**Comment by pollygee** [comment]
Thanks so much!

**Pull request merged**
